version: '3'

services:
  mlflow:
    build:
       context: .
       dockerfile: ./docker-files/Dockerfile.mlflow
    command: mlflow server -h 0.0.0.0 -p 5000 --backend-store-uri=sqlite:///mlflow.db
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./src:/app/your_codebase
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000

  mageai:
    image: mageai/mageai:latest
    ports:
      - "6789:6789"
    volumes:
      - ./src:/home/src/your_codebase
    environment:
      - USER_CODE_PATH=/home/src/your_codebase
  your_app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./your_codebase:/app/your_codebase
    depends_on:
      - mlflow
      - mageai
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MAGE_API_URL=http://mageai:6789
      