# version: '3'
# services:
#   mlflow:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     networks:
#       - backend-server
    
#     command: mlflow server -h 0.0.0.0 -p 5000 --backend-store-uri=sqlite:///mlflow.db
#     restart: always
# networks:
#   backend-server:

version: '3.8'

services:
  mlflow:
    build:
       context: .
       dockerfile: Dockerfile
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      MLFLOW_ARTIFACT_ROOT: /mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    networks:
      - backend-server

volumes:
  postgres_data:
  mlflow_artifacts:

networks:
  backend-server:
