FROM python:3.9

WORKDIR /app

#COPY requirements.txt .
#RUN pip install -r requirements.txt


COPY ./src /home/your_codebase
COPY ./dataset/itineraries_small.csv /home/your_codebase/dataset
#CMD ["python", "your_codebase/your_main_script.py"]