FROM python:3.9

WORKDIR /app

#COPY requirements.txt .
#RUN pip install -r requirements.txt

COPY ./src /app/your_codebase
COPY ./dataset /app/your_codebase/dataset

#CMD ["python", "your_codebase/your_main_script.py"]